import { green, blue, blueGrey, orange, red, grey } from '@material-ui/core/colors';

export const vcColorPalette = {
  white: '#FFFFFF',
  black: '#000000',
  border: '#eaeaea',

  text: {
    // primary: '#1F1F1F',
    // secondary: '#9B9B9B',
    primary: blueGrey[900],
    secondary: blueGrey[600],
    // link: blue[600]
  },
  background: {
    other: '#eaeaea',
    paper: '#ffffff',
    canvas: '#fafafa',
    default: '#F5F5FA',
    lightGrey: '#FAFAFD',
  },

  common: {
    selectedGray: '#E8E8EF',
    red: '#EB563B',
    dark: '#1F1F1F',
    shade: '#868686',
    lightGray: grey[200],
    grey: '#A1AEB7',
    darkGrey: '#424b5a',
    backgroundGray: '#D8D8D8',
    orange: orange[500],
    chartColor0: '#4884D1',
    chartColor1: '#E05E2E',
    chartColor2: '#1D9C66',
    chartColor3: '#E53068',
    chartColor4: '#8044C3',
    chartColor5: '#1994A5',
    chartColor6: '#4040F0',
    chartColor7: '#AF1E8C',
    chartColor8: '#5A7580',
    chartColor9: '#E65055',
    lightGrey: '#F4F3F4',
    chartLine: '#5B6772',
    donutRed: '#E33F2E',
    donutGreen: '#39B4B8',
    donutYellow: '#ECA125',
    slate: '#434E58',
    brandChartColor1: '#0F2F40',
    brandChartColor2: '#068587',
    brandChartColor3: '#8DD7CF',
    brandChartColorDark3: '#1AAE9F',
    brandChartColor4: '#72CAC7',
    brandChartColor5: '#EB563B',
    brandChartColor6: '#FFC61A',
    brandChartColor7: '#7F2083',
    brandChartColor8: '#C53F99',
    brandChartColor9: '#4040F0',
    brandChartColorGrey: '#C3CFD9',
    brandChartColorDark9: '#9BA9B5',
    pink: '#F24161',
    blue: '#4d49ff',
    darkGrey1: '#403F77',
    darkGrey2: '#181C2C',
  },
  grey: {
    darker: '#191928',
    dark: '#41415A',
    base: '#6E7396',
    light: '#B9B9CD',
    lighter: '#EBEBF5',
  },
  violet: {
    darker: '#14144B',
    dark: '#28289B',
    base: '#4B4BFF',
    light: '#A5A5FF',
    lighter: '#F0F0FF',
  },
  magenta: {
    darker: '#46141E',
    dark: '#91283C',
    base: '#F04164',
    light: '#FAA0B4',
    lighter: '#FFEBF0',
  },
  skyBlue: {
    darker: '#00284B',
    dark: '#005FB9',
    base: '#00A0FF',
    light: '#82D2FF',
    lighter: '#E6F5FF',
  },
  green: {
    darker: '#053719',
    dark: '#0A6E32',
    base: '#0FB450',
    light: '#6ED78C',
    lighter: '#E6FAF0',
  },
};

export default {
  contrastThreshold: 3,
  tonalOffset: 0.2,

  black: vcColorPalette.black,
  white: vcColorPalette.white,
  border: vcColorPalette.border,
  background: vcColorPalette.background,
  text: vcColorPalette.text,

  vc: {
    grey: vcColorPalette.grey,
    violet: vcColorPalette.violet,
    magenta: vcColorPalette.magenta,
    skyBlue: vcColorPalette.skyBlue,
    green: vcColorPalette.green,
  },

  common: {
    black: vcColorPalette.black,
    white: vcColorPalette.white,
    ...vcColorPalette.common,
  },

  primary: {
    light: vcColorPalette.violet.light,
    main: vcColorPalette.violet.base,
    dark: vcColorPalette.violet.dark,
    contrastText: vcColorPalette.white,
  },
  secondary: {
    light: vcColorPalette.magenta.light,
    main: vcColorPalette.magenta.base,
    dark: vcColorPalette.magenta.dark,
    contrastText: vcColorPalette.black,
  },
  success: {
    light: green[400],
    main: green[600],
    dark: green[900],
    contrastText: vcColorPalette.white,
  },
  info: {
    light: blue[400],
    main: blue[600],
    dark: blue[900],
    contrastText: vcColorPalette.white,
  },
  warning: {
    light: orange[400],
    main: orange[600],
    dark: orange[900],
    contrastText: vcColorPalette.white,
  },
  error: {
    light: red[400],
    main: red[600],
    dark: red[900],
    contrastText: vcColorPalette.white,
  },
  action: {
    active: vcColorPalette.white,
    hover: 'rgba(255, 255, 255, 0.08)',
    hoverOpacity: 0.08,
    selected: 'rgba(0, 0, 0, 0.16)',
    selectedOpacity: 0.16,
    disabled: 'rgba(0, 0, 0, 0.3)',
    disabledBackground: 'rgba(0, 0, 0, 0.12)',
    disabledOpacity: 0.38,
    focus: 'rgba(255, 255, 255, 0.12)',
    focusOpacity: 0.12,
    activatedOpacity: 0.24,
  },
};
