version: "3"

services:
  backend:
    container_name: forte-dev-hasura
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      PORT: ${PORT}
    ports:
      - "8080:8080"
    restart: on-failure

  db:
    container_name: forte-dev-hasura-db
    image: postgres:11.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
